"""Framework-neutral contracts and lifecycle primitives for the dashboard."""

from .contracts import (
    AnalysisProvider,
    Importer,
    SourceCapabilities,
    SourceError,
    SourceEvent,
    SourceEventKind,
    SourceEventQueue,
    SourceHealth,
    SourceQueueStats,
    SourceState,
    TelemetrySource,
    UnitConverter,
    UnsupportedSourceOperation,
    WidgetFactory,
)
from .lifecycle import (
    BackgroundService,
    CancellationRequested,
    CancellationToken,
    ServiceEvent,
    ServiceFailure,
)
from .protocol import (
    CURRENT_PROTOCOL_VERSION,
    MAGIC,
    MAX_PAYLOAD_BYTES,
    PROTOCOL_NAME,
    FrameKind,
    FrameStreamDecoder,
    IntegrityError,
    ProtocolDecodeError,
    ProtocolError,
    ProtocolFrame,
    TruncatedFrameError,
    UnsupportedProtocolVersion,
    decode_frame,
    encode_frame,
    sequence_is_after,
    timestamp_is_after,
)
from .registries import RegistryBundle
from .registry import FactoryError, Registry, RegistryError
from .signals import (
    KNOWN_SIGNAL_TYPES,
    SignalAvailability,
    SignalDescriptor,
    SignalRegistry,
    SignalSample,
    SignalSchema,
    SignalSchemaError,
    SignalSeries,
)

__all__ = [
    "AnalysisProvider",
    "BackgroundService",
    "CURRENT_PROTOCOL_VERSION",
    "CancellationRequested",
    "CancellationToken",
    "FactoryError",
    "FrameKind",
    "FrameStreamDecoder",
    "Importer",
    "IntegrityError",
    "MAGIC",
    "MAX_PAYLOAD_BYTES",
    "PROTOCOL_NAME",
    "ProtocolDecodeError",
    "ProtocolError",
    "ProtocolFrame",
    "Registry",
    "RegistryBundle",
    "RegistryError",
    "SourceCapabilities",
    "SourceError",
    "SourceEvent",
    "SourceEventKind",
    "SourceEventQueue",
    "SourceHealth",
    "SourceQueueStats",
    "SourceState",
    "KNOWN_SIGNAL_TYPES",
    "SignalAvailability",
    "SignalDescriptor",
    "SignalRegistry",
    "SignalSample",
    "SignalSchema",
    "SignalSchemaError",
    "SignalSeries",
    "ServiceEvent",
    "ServiceFailure",
    "TelemetrySource",
    "TruncatedFrameError",
    "UnitConverter",
    "UnsupportedSourceOperation",
    "UnsupportedProtocolVersion",
    "WidgetFactory",
    "decode_frame",
    "encode_frame",
    "sequence_is_after",
    "timestamp_is_after",
]
